version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  function:
    image: dockerexpfunction:0.4
    container_name: dockercomposeexpfunction
    environment:
      redisConnectionString: redis:6379
      redisInstanceName: DockerComposeFuncCache
    ports:
      - 9099:80
    depends_on:
      - redis